[dependencies]
"php/php" = "=8.4.0"

[fs]
"/app/" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
# Points the router (-t) directly to Laravel's public directory
main-args = ["-t", "/app/public", "-S", "localhost:8080"]
