@extends(backpack_view('blank'))
@section('header')<section class="container-fluid"><h1>Approvals & moderation</h1><p class="text-muted">Review shops. Approving a shop also approves its products and uploads.</p></section>@endsection
@section('content')
@include('admin.messages')
<form method="get" class="d-flex gap-2 mb-3"><input type="hidden" name="type" value="shops"><select name="status" class="form-select" aria-label="Status">@foreach(['pending','approved','rejected','frozen'] as $option)<option @selected($status === $option)>{{ $option }}</option>@endforeach</select><button class="btn btn-outline-primary">View shops</button></form>
<div class="card mb-4"><div class="card-body"><form method="post" action="{{ route('moderation.store') }}">@csrf<input type="hidden" name="type" value="{{ $type }}">
<div class="table-responsive"><table class="table"><thead><tr><th>Select</th><th>Name</th><th>Details</th><th>Status</th></tr></thead><tbody>
@forelse($records as $record)<tr><td><input type="checkbox" class="form-check-input" name="ids[]" value="{{ $record->id }}" aria-label="Select {{ $record->name }}"></td><td><a href="{{ route('shop.show', $record) }}">{{ $record->name }}</a></td><td>{{ $record->location }}</td><td>{{ $record->status }}</td></tr>@empty<tr><td colspan="4">No {{ $status }} shops to review.</td></tr>@endforelse</tbody></table></div>
<label class="form-label w-100">Decision<select name="status" class="form-select"><option value="approved">Approve / release freeze</option><option value="rejected">Reject</option><option value="frozen">Freeze</option></select></label><label class="form-label w-100">Reason (required for rejection or freeze)<textarea class="form-control" name="reason" maxlength="2000">{{ old('reason') }}</textarea></label><button class="btn btn-primary">Apply to selected records</button></form>{{ $records->links() }}</div></div>
<div class="card mb-4"><div class="card-body"><h3>Recent moderation activity</h3>@foreach($logs as $log)<p class="border-bottom pb-2"><strong>{{ ucfirst($log->status) }}</strong> · {{ $log->subject_type }} · {{ $log->subject_id }}<br>{{ $log->reason }} <small class="text-muted">{{ $log->created_at }}</small></p>@endforeach</div></div>
@endsection
