@extends('storefront.layout')
@section('content')
<section class="hero"><div><p class="eyebrow">● LOCAL SHOPS, A LITTLE CLOSER</p><h1>Good things.<br>Right around<br><em>your corner.</em></h1><p class="hero-description">Discover independent shops, find your everyday essentials, and support the people behind them.</p><a class="button" href="#shops">Find your next favorite shop ↗</a></div>
<div class="hero-art" aria-hidden="true"><div class="art-note">THE NEIGHBORHOOD COLLECTION<br><strong>Always something good.</strong></div><div class="shop-drawing"><div class="awning"><i></i><i></i><i></i><i></i><i></i></div><div class="shop-sign">YOUR LOCAL FAVORITE</div><div class="shop-front"><div class="shop-window"><span>✦</span><small>fresh finds<br>daily</small></div><div class="shop-door"><span>OPEN</span></div></div></div><div class="art-label">Independent by nature.<br>Connected by Storex.</div><div class="sun">✳</div></div></section>
<div class="promise-strip"><span>✦ Discover local businesses</span><span>✦ Shop approved products</span><span>✦ Pay securely with Paystack</span></div>
<section id="shops" class="shop-section"><div class="section-heading"><div><p class="eyebrow">MEET YOUR NEIGHBORHOOD</p><h2>A shop for your everyday.</h2></div><form class="search" method="get"><input name="q" value="{{ $search }}" placeholder="Find a shop…" aria-label="Search shops"><button aria-label="Search">↗</button></form></div>
<div class="shop-grid">@forelse($shops as $shop)<a class="shop-card" href="{{ route('shops.show', $shop->slug) }}"><div class="shop-cover">@if($shop->banner)<img src="{{ Storage::disk('public')->url(Str::start($shop->banner, 'shops/')) }}" alt="{{ $shop->name }}" loading="lazy">@else<span class="cover-initial">{{ mb_substr($shop->name, 0, 1) }}</span>@endif<span class="shop-count">{{ $shop->products_count }} finds</span></div><div class="shop-card-body"><p class="eyebrow">{{ $shop->location }}</p><h3>{{ $shop->name }} ↗</h3><p>{{ Str::limit($shop->description ?: 'Explore the latest from this local shop.', 110) }}</p></div></a>
@empty<div class="empty-state"><span>✳</span><h3>{{ $search ? 'No shops found.' : 'A new neighborhood is taking shape.' }}</h3><p>{{ $search ? 'Try another shop name.' : 'Be one of the first independent shops on Storex.' }}</p><a href="{{ backpack_url('register') }}" class="button secondary">Open your shop ↗</a></div>@endforelse</div>{{ $shops->links() }}
</section><section class="owner-banner"><div><p class="eyebrow">FOR THE PEOPLE BEHIND THE COUNTER</p><h2>Your shop. A whole new storefront.</h2><p>Manage your stock, make sales, and bring your business online.</p></div><a class="button" href="{{ backpack_url('register') }}">Start your shop ↗</a></section>
@endsection
