@extends('storefront.layout')
@section('title', $shop->name.' — Storex')
@section('content')
<section class="store-heading">@if($shop->banner)<img class="store-banner" src="{{ Storage::disk('public')->url(Str::start($shop->banner, 'shops/')) }}" alt="">@endif
<div class="store-identity">@if($shop->logo)<img class="store-logo" src="{{ Storage::disk('public')->url(Str::start($shop->logo, 'shops/')) }}" alt="{{ $shop->name }} logo">@endif<div><p class="eyebrow">{{ $shop->location }}</p><h1>{{ $shop->name }}</h1><p class="preserve-lines">{{ $shop->description }}</p><p>{{ $shop->contacts }} · <a href="mailto:{{ $shop->email }}">{{ $shop->email }}</a></p></div></div></section>
<section class="shop-section"><div class="section-heading"><div><p class="eyebrow">CURATED BY YOUR LOCAL SHOP</p><h2>Find something good.</h2></div><form class="search" method="get"><input name="q" value="{{ $search }}" placeholder="Search products or barcode" aria-label="Search products"><button aria-label="Search">↗</button></form></div>
<form method="post" action="{{ route('checkout.store', $shop->slug) }}">@csrf
<div class="product-grid">@forelse($products as $product)<article class="product-card"><div class="product-image">@if($product->image)<img src="{{ Storage::disk('public')->url(Str::start($product->image, 'products/')) }}" alt="{{ $product->name }}" loading="lazy">@else<span aria-hidden="true">✦</span>@endif</div><div class="product-body"><h3>{{ $product->name }}</h3><p class="preserve-lines">{{ $product->description }}</p><div class="product-price"><strong>{{ $shop->currency }} {{ number_format((float)$product->selling_price, 2) }}</strong><span>{{ $product->quantity === null ? 'Available' : ($product->quantity > 0 ? $product->quantity.' in stock' : 'Sold out') }}</span></div>
@if($product->quantity !== 0)<label class="quantity-label">Quantity<input type="number" name="items[{{ $product->id }}]" value="{{ old('items.'.$product->id, 0) }}" min="0" max="{{ min($product->quantity ?? 10000, 10000) }}" aria-label="Quantity for {{ $product->name }}"></label>@endif</div></article>@empty<div class="empty-state"><h3>No products to show yet.</h3><p>Check back soon for more good things.</p></div>@endforelse</div>
{{ $products->links() }}
@if($products->isNotEmpty())<section class="checkout-box"><div><p class="eyebrow">READY WHEN YOU ARE</p><h2>Make it yours.</h2><p>Choose quantities above, then enter your details. Your total is confirmed on Paystack before you pay.</p><p class="small-text">Stock is reserved for 15 minutes during checkout. Contact the shop to arrange collection or delivery. Submit the products on this page before browsing another page.</p></div><div class="checkout-fields">
<label>Full name<input name="customer_name" required maxlength="150" autocomplete="name" value="{{ old('customer_name') }}"></label><label>Email address<input type="email" name="customer_email" required autocomplete="email" value="{{ old('customer_email') }}"></label><label>Phone (optional)<input name="customer_phone" autocomplete="tel" value="{{ old('customer_phone') }}"></label><label>Delivery address or collection note (optional)<textarea name="delivery_address" rows="3">{{ old('delivery_address') }}</textarea></label>
@if($shop->paystack_secret_key)<button class="button" type="submit">Continue to secure payment ↗</button>@else<p class="notice">Online payments are not enabled yet. Contact the shop to purchase.</p>@endif</div></section>@endif</form></section>
@endsection
